### ISSUE TITLE
Readme lab requires submitted work

### ISSUE THREAD

**Issue by weezwo** [learn-co-curriculum/traversing-nested-objects#14]
Maybe there is something I am missing, but perusing the GitHub files seems to confirm that there is nothing to submit for this lesson, but it requires submitted work for completion.

**Comment by weezwo** [comment]
Here is a screenshot: <img width="1280" alt="screen shot 2017-04-25 at 4 38 17 pm" src="https://cloud.githubusercontent.com/assets/19954790/25406706/ab4bade6-29d5-11e7-91d5-b12bb7190acc.png">

**Comment by joelcowie** [comment]
@aturkewi I believe this lab needs to be re-classified as a readme

**Comment by aturkewi** [comment]
Toggled to a readme :)

Thanks for letting me know.
