### ISSUE TITLE
Update while loop condition for function find

### ISSUE THREAD

**Issue by helloRupa** [learn-co-curriculum/traversing-nested-objects#19]
At the end of the lesson:
If you test function find() with an array containing a 0, the while loop will exit without fully traversing the array due to falsiness. Update the while loop condition to while (current || current === 0) and it works with 0.

**Comment by sgharms** [comment]
Good debugging,  @helloRupa, will integrate.

**Comment by sgharms** [comment]
Fixed in 6a9aa3c
