### ISSUE TITLE
This lesson displays as a lab, but it is just a readme lesson

### ISSUE THREAD

**Issue by braden337** [learn-co-curriculum/traversing-nested-objects#2]
When you run `learn open` it just opens up the readme in the web browser, no tests to run, so you can't complete the lesson

**Comment by AnnJohn** [comment]
hi  @braden337  this isn't a lab so no need to fork anything.

**Comment by braden337** [comment]
@AnnJohn since it isn't a lab though, it should have the button to "Finish Reading". The sidebar on that page is like the sidebar you would find on a lab, not like the sidebar you would find on a lesson that you just need to read

## Example of another reading lesson sidebar:

![not_lab](https://cloud.githubusercontent.com/assets/2252884/17786463/8e43e344-654a-11e6-9e48-67de40c98d14.jpg)

## What is actually on the Traversing Nested Objects lesson page:

![image](https://cloud.githubusercontent.com/assets/2252884/17314341/351c6e0e-5829-11e6-9f97-6c4d7b08872c.png)
