### ISSUE TITLE
Clarification Needed

### ISSUE THREAD

**Issue by SimonAble** [learn-co-curriculum/traversing-nested-objects#20]
In this lesson, we are taught that we can implement 'find' functions using the parameters (array, criteriaFN). I believe some clarification on how to implement criteriaFN is needed. The student is not taught that you can declare a function within the parameters of another. Simply providing a quick explanation of how to implement the search would clear up a lot of confusion.

**Comment by sgharms** [comment]
We've integrated your suggestion. Thanks.
