### ISSUE TITLE
A couple copyediting issues to check on this lesson's text 

### ISSUE THREAD

**Issue by s-blais** [learn-co-curriculum/traversing-nested-objects#27]
Hi, I found a couple hiccups in this lesson's text:

About halfway, it states in the code-view box:

We should now see the `yearsHeld` value:
```javascript
2

When (I'm fairly certain that) it wants to say:

person.occupation.yearsHeld

and the "We should… " wants to be outside the code-view box.

Also, the first and second paragraphs in the "Arrays in Arrays" section are almost identical.

Thanks!

**Comment by s-blais** [comment]
Sorry about the extra formatting being triggered by the text that I input

some screenshots... 

![Screen Shot 2019-06-17 at 10 45 26 AM](https://user-images.githubusercontent.com/51341914/59613738-6ead2280-90ed-11e9-9e0d-37af357d386f.png)
![Screen Shot 2019-06-17 at 10 48 57 AM](https://user-images.githubusercontent.com/51341914/59613813-9308ff00-90ed-11e9-9cbd-c7d6b65eca85.png)

**Comment by maxwellbenton** [comment]
Hi @s-blais,

Thank you for spotting these issues and providing feedback (along with screenshots!). We've updated this lesson and corrected the markdown errors that were causing these display issues and believe they are now resolved.

Thank you for contributing to a Learn.co lesson!
