### ISSUE TITLE
explain criteriaFn earlier

### ISSUE THREAD

**Issue by bolloland** [learn-co-curriculum/traversing-nested-objects#30]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

Add a link to the assignment in Canvas here.

## What should be changed?

when introducing the "Find an Element in a Nested Array" section, 
can you give an example of what criteriaFn would do, prior to showing the code?
It's not defined, so you should explain that the user would include their own function based on the returned data they find. Thanks. It's not shown 'til later and gets a little confusing.

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the GitHub repo and believe your issue to have been resolved. Note, however, that if you are working in Canvas the changes may not show up there.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
